# The words to handle as swear words
block_words:
  - Heil Hitler
  - Hure
  - Huso
  - Bastard
  - Fotze
  - fick
  - Schlampe
  - Wichser
  - Schwuchtel
  - Spast
  - Arsch
  - Titte
  - Nutte
  - Schwanz
  - suck my dick
  - fuck
  - horny
  - slut
  - slag
  - boob
  - pussy
  - vagina
  - faggot
  - penis
  - bugger
  - cunt
  - nigger
  - nigga
  - jerk
  - anal
  - wanker
  - tosser
  - cock
  - whore
  - bitch
  - asshole
  - twat
  - sperm
  - spunk
  - testicle
  - milf
  - gilf
  - retard
  - anus
  - prick
# The similarity to the last message, in percent, at which a message is blocked
similarity_percentage: 70
# Commands to handle as chat
chat_commands:
  - h
  - handel
  - handelchat
  - handelschat
  - e
  - g
  - global
  - l
  - local
# DO NOT CHANGE THIS
config_version: null