name: ChatSystem
version: '${version}'
main: de.leonheuer.skycave.chatsystem.ChatSystem
api-version: 1.18
authors: [ Hakuyamu ]

commands:
  chatsystem:
    permission: skycave.chat.command.chatsystem

permissions:
  skycave.chat.staff:
    description: "staff permission"
  skycave.chat.bypass:
    children:
      - characters
      - spam
      - swear
      - move
      - wait
      - grammar